<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Electrical Parts
            [
                'name' => 'Kawasaki Barako 175 Stator (Charging Unit)',
                'category' => 'Electrical Parts',
                'condition' => 'New',
                'fitment' => 'Kawasaki Barako 175',
                'price' => 720.00,
                'stock' => 12,
                'details' => 'OEM fit stator for charging system. Great for replacing worn electrical units.',
                'icon' => '⚡',
                'is_available' => true,
            ],
            [
                'name' => 'Rectifier / Regulator for Barako 175',
                'category' => 'Electrical Parts',
                'condition' => 'New',
                'fitment' => 'Kawasaki Barako 175',
                'price' => 225.00,
                'stock' => 20,
                'details' => 'Keeps battery charging stable — essential electrical replacement.',
                'icon' => '⚡',
                'is_available' => true,
            ],
            [
                'name' => 'Kawasaki Barako 175 Ignition Switch',
                'category' => 'Electrical Parts',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 200.00,
                'stock' => 15,
                'details' => 'Genuine replacement ignition switch — high demand part.',
                'icon' => '🔑',
                'is_available' => true,
            ],
            [
                'name' => 'Spark Plug (Genuine Kawasaki)',
                'category' => 'Electrical Parts',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 150.00,
                'stock' => 0,
                'details' => 'Original equipment manufacturer spark plug for optimal engine performance.',
                'icon' => '✨',
                'is_available' => false,
            ],
            [
                'name' => 'LED Headlight Assembly',
                'category' => 'Electrical Parts',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 850.00,
                'stock' => 8,
                'details' => 'Bright LED headlight with better visibility and longer lifespan.',
                'icon' => '💡',
                'is_available' => true,
            ],

            // Engine Parts
            [
                'name' => 'Kawasaki Barako BC175 Clutch Lining',
                'category' => 'Engine Parts',
                'condition' => 'New',
                'fitment' => 'BC‑175',
                'price' => 500.00,
                'stock' => 8,
                'details' => 'Quality clutch lining — ideal for smoother gear engagement.',
                'icon' => '⚙️',
                'is_available' => true,
            ],
            [
                'name' => 'Kawasaki Barako 175 Carburetor Assembly',
                'category' => 'Engine Parts',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 1250.00,
                'stock' => 5,
                'details' => 'Durable carburetor — top choice for rebuilds or replacements.',
                'icon' => '⚙️',
                'is_available' => true,
            ],
            [
                'name' => 'Air Filter Element (Genuine)',
                'category' => 'Engine Parts',
                'condition' => 'New',
                'fitment' => 'Barako B1/B2',
                'price' => 100.00,
                'stock' => 40,
                'details' => 'OEM Kawasaki air filter — keeps engine clean and efficient.',
                'icon' => '🌬️',
                'is_available' => true,
            ],
            [
                'name' => 'Piston and Ring Set',
                'category' => 'Engine Parts',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 2100.00,
                'stock' => 3,
                'details' => 'Premium piston and ring set for complete engine rebuild.',
                'icon' => '⚙️',
                'is_available' => true,
            ],
            [
                'name' => 'Gasket Kit (Full Set)',
                'category' => 'Engine Parts',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 450.00,
                'stock' => 0,
                'details' => 'Complete gasket kit for all engine sealing points.',
                'icon' => '🔧',
                'is_available' => false,
            ],
            [
                'name' => 'Valve Assembly',
                'category' => 'Engine Parts',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 380.00,
                'stock' => 6,
                'details' => 'Precision engineered valve assembly for optimal performance.',
                'icon' => '⚙️',
                'is_available' => true,
            ],

            // Drivetrain Parts
            [
                'name' => 'Kawasaki Barako 175 Sprocket 48T',
                'category' => 'Drivetrain',
                'condition' => 'New',
                'fitment' => 'Kawasaki Barako BC‑175',
                'price' => 270.00,
                'stock' => 34,
                'details' => 'Genuine sprocket with proper tooth count. Perfect for drive train replacement.',
                'icon' => '🔄',
                'is_available' => true,
            ],
            [
                'name' => 'Chain Assembly (Roller Chain)',
                'category' => 'Drivetrain',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 180.00,
                'stock' => 22,
                'details' => 'Heavy-duty roller chain with proper pitch for Barako 175.',
                'icon' => '🔗',
                'is_available' => true,
            ],
            [
                'name' => 'Centrifugal Clutch',
                'category' => 'Drivetrain',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 650.00,
                'stock' => 0,
                'details' => 'Automatic clutch engagement system for smooth acceleration.',
                'icon' => '🔄',
                'is_available' => false,
            ],
            [
                'name' => 'Belt Drive Kit',
                'category' => 'Drivetrain',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 420.00,
                'stock' => 5,
                'details' => 'Modern belt drive alternative with reduced maintenance.',
                'icon' => '🔄',
                'is_available' => true,
            ],

            // Tricycle Accessories
            [
                'name' => 'Brake & Clutch Pair Levers (Stock)',
                'category' => 'Tricycle Accessories',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 58.00,
                'stock' => 120,
                'details' => 'Standard handle levers — essential wear parts.',
                'icon' => '🎯',
                'is_available' => true,
            ],
            [
                'name' => 'Comfortable Seat Cushion',
                'category' => 'Tricycle Accessories',
                'condition' => 'New',
                'fitment' => 'Universal Barako',
                'price' => 450.00,
                'stock' => 18,
                'details' => 'Premium cushioned seat for enhanced rider comfort during long journeys.',
                'icon' => '🪑',
                'is_available' => true,
            ],
            [
                'name' => 'Custom Dashboard Panel',
                'category' => 'Tricycle Accessories',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 780.00,
                'stock' => 0,
                'details' => 'Custom dashboard with speedometer and fuel gauge.',
                'icon' => '📊',
                'is_available' => false,
            ],
            [
                'name' => 'Reinforced Handlebar Assembly',
                'category' => 'Tricycle Accessories',
                'condition' => 'New',
                'fitment' => 'Universal Barako',
                'price' => 320.00,
                'stock' => 14,
                'details' => 'Heavy-duty handlebar for better control and durability.',
                'icon' => '🎯',
                'is_available' => true,
            ],
            [
                'name' => 'Side Mirror Pair',
                'category' => 'Tricycle Accessories',
                'condition' => 'New',
                'fitment' => 'Universal',
                'price' => 190.00,
                'stock' => 25,
                'details' => 'Wide-angle mirrors for better visibility.',
                'icon' => '🪞',
                'is_available' => true,
            ],
            [
                'name' => 'Sidecar Attachment Kit',
                'category' => 'Tricycle Accessories',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 2500.00,
                'stock' => 2,
                'details' => 'Complete sidecar kit with mounting hardware.',
                'icon' => '🚲',
                'is_available' => true,
            ],

            // Brake System
            [
                'name' => 'Front Brake Caliper',
                'category' => 'Brake System',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 480.00,
                'stock' => 11,
                'details' => 'Hydraulic disc brake caliper with OEM specifications.',
                'icon' => '🛑',
                'is_available' => true,
            ],
            [
                'name' => 'Brake Pads (Set of 2)',
                'category' => 'Brake System',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 210.00,
                'stock' => 45,
                'details' => 'High-performance brake pads for reliable stopping power.',
                'icon' => '🛑',
                'is_available' => true,
            ],
            [
                'name' => 'Brake Fluid (1 Liter)',
                'category' => 'Brake System',
                'condition' => 'New',
                'fitment' => 'Universal',
                'price' => 95.00,
                'stock' => 0,
                'details' => 'Premium DOT 4 brake fluid for hydraulic systems.',
                'icon' => '🛑',
                'is_available' => false,
            ],
            [
                'name' => 'Brake Master Cylinder',
                'category' => 'Brake System',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 750.00,
                'stock' => 4,
                'details' => 'Original brake master cylinder assembly.',
                'icon' => '🛑',
                'is_available' => true,
            ],

            // Suspension & Frame
            [
                'name' => 'Front Shock Absorber',
                'category' => 'Suspension',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 890.00,
                'stock' => 7,
                'details' => 'Adjustable suspension for smoother riding experience.',
                'icon' => '🔧',
                'is_available' => true,
            ],
            [
                'name' => 'Rear Shock Absorber',
                'category' => 'Suspension',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 920.00,
                'stock' => 0,
                'details' => 'Heavy-duty rear suspension for cargo capacity.',
                'icon' => '🔧',
                'is_available' => false,
            ],

            // Tires & Wheels
            [
                'name' => 'Front Tire (Tube Type)',
                'category' => 'Tires & Wheels',
                'condition' => 'New',
                'fitment' => 'Barako 175 (17 inch)',
                'price' => 850.00,
                'stock' => 9,
                'details' => 'Durable tube-type tire with good traction.',
                'icon' => '🛞',
                'is_available' => true,
            ],
            [
                'name' => 'Rear Tire (Tube Type)',
                'category' => 'Tires & Wheels',
                'condition' => 'New',
                'fitment' => 'Barako 175 (17 inch)',
                'price' => 950.00,
                'stock' => 6,
                'details' => 'Heavy-duty rear tire designed for tricycle loads.',
                'icon' => '🛞',
                'is_available' => true,
            ],
            [
                'name' => 'Inner Tube Kit (3-pack)',
                'category' => 'Tires & Wheels',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 320.00,
                'stock' => 0,
                'details' => 'Replacement inner tubes for all three wheels.',
                'icon' => '🛞',
                'is_available' => false,
            ],
            [
                'name' => 'Wheel Rim Assembly',
                'category' => 'Tires & Wheels',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 1200.00,
                'stock' => 3,
                'details' => 'Complete wheel rim with bearings.',
                'icon' => '🛞',
                'is_available' => true,
            ],

            // Fuel System
            [
                'name' => 'Fuel Tank Assembly',
                'category' => 'Fuel System',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 1650.00,
                'stock' => 2,
                'details' => '10-liter fuel tank with integrated fuel filter.',
                'icon' => '⛽',
                'is_available' => true,
            ],
            [
                'name' => 'Fuel Pump (Electric)',
                'category' => 'Fuel System',
                'condition' => 'New',
                'fitment' => 'Barako 175 FI Models',
                'price' => 580.00,
                'stock' => 5,
                'details' => 'Electric fuel pump for fuel-injected models.',
                'icon' => '⛽',
                'is_available' => true,
            ],
            [
                'name' => 'Fuel Filter Cartridge',
                'category' => 'Fuel System',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 85.00,
                'stock' => 50,
                'details' => 'Replacement fuel filter for clean fuel delivery.',
                'icon' => '⛽',
                'is_available' => true,
            ],

            // Tools & Maintenance
            [
                'name' => 'Complete Tool Kit for Barako',
                'category' => 'Tools & Maintenance',
                'condition' => 'New',
                'fitment' => 'Universal',
                'price' => 1100.00,
                'stock' => 8,
                'details' => 'Professional grade tool set with 50+ tools for maintenance.',
                'icon' => '🔧',
                'is_available' => true,
            ],
            [
                'name' => 'Engine Oil (4L Premium)',
                'category' => 'Tools & Maintenance',
                'condition' => 'New',
                'fitment' => 'Universal',
                'price' => 280.00,
                'stock' => 25,
                'details' => 'High-quality synthetic motor oil for optimal engine protection.',
                'icon' => '🛢️',
                'is_available' => true,
            ],
            [
                'name' => 'Transmission Fluid (1L)',
                'category' => 'Tools & Maintenance',
                'condition' => 'New',
                'fitment' => 'Barako 175',
                'price' => 220.00,
                'stock' => 0,
                'details' => 'Specialized transmission fluid for smooth gear shifting.',
                'icon' => '🛢️',
                'is_available' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
